# Generated by Django 3.2.15 on 2022-12-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder', models.CharField(max_length=256, verbose_name='开发商')),
                ('houseType', models.CharField(max_length=64, verbose_name='户型')),
                ('area', models.CharField(max_length=20, verbose_name='面积')),
                ('direction', models.CharField(max_length=20, verbose_name='朝向')),
                ('decoration', models.CharField(max_length=20, verbose_name='装修')),
                ('floor', models.CharField(max_length=60, verbose_name='楼层')),
                ('year', models.CharField(max_length=20, verbose_name='年份')),
                ('structure', models.CharField(max_length=20, verbose_name='结构')),
                ('total_price', models.IntegerField(verbose_name='售价(万元)')),
                ('unit_price', models.CharField(max_length=20, verbose_name='单价(元/平方米)')),
            ],
        ),
    ]
